apiVersion: v1
data:
  components: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      creationTimestamp: null
      labels:
        aadpodidbinding: capz-controller-aadpodidentity-selector
        cluster.x-k8s.io/provider: infrastructure-azure
        clusterctl.cluster.x-k8s.io: ""
        control-plane: capz-controller-manager
      name: capz-controller-manager
      namespace: openshift-cluster-api
    spec:
      replicas: 1
      selector:
        matchLabels:
          cluster.x-k8s.io/provider: infrastructure-azure
          control-plane: capz-controller-manager
      strategy: {}
      template:
        metadata:
          annotations:
            kubectl.kubernetes.io/default-container: manager
            target.workload.openshift.io/management: '{"effect": "PreferredDuringScheduling"}'
          creationTimestamp: null
          labels:
            aadpodidbinding: capz-controller-aadpodidentity-selector
            cluster.x-k8s.io/provider: infrastructure-azure
            control-plane: capz-controller-manager
        spec:
          containers:
          - args:
            - --leader-elect
            - --metrics-bind-addr=localhost:8080
            - --v=0
            env:
            - name: AZURE_SUBSCRIPTION_ID
              valueFrom:
                secretKeyRef:
                  key: azure_subscription_id
                  name: capz-manager-bootstrap-credentials
            - name: AZURE_TENANT_ID
              valueFrom:
                secretKeyRef:
                  key: azure_tenant_id
                  name: capz-manager-bootstrap-credentials
            - name: AZURE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  key: azure_client_id
                  name: capz-manager-bootstrap-credentials
            - name: AZURE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  key: azure_client_secret
                  name: capz-manager-bootstrap-credentials
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            image: to.be/replaced:v99
            imagePullPolicy: Always
            livenessProbe:
              httpGet:
                path: /healthz
                port: healthz
              initialDelaySeconds: 10
              periodSeconds: 10
            name: manager
            ports:
            - containerPort: 9443
              name: webhook-server
              protocol: TCP
            - containerPort: 9440
              name: healthz
              protocol: TCP
            readinessProbe:
              httpGet:
                path: /readyz
                port: healthz
              initialDelaySeconds: 10
              periodSeconds: 10
            resources:
              requests:
                cpu: 10m
                memory: 50Mi
            volumeMounts:
            - mountPath: /tmp/k8s-webhook-server/serving-certs
              name: cert
              readOnly: true
          priorityClassName: system-cluster-critical
          serviceAccountName: capz-manager
          terminationGracePeriodSeconds: 10
          tolerations:
          - effect: NoSchedule
            key: node-role.kubernetes.io/master
          - effect: NoSchedule
            key: node-role.kubernetes.io/control-plane
          volumes:
          - name: cert
            secret:
              defaultMode: 420
              secretName: capz-webhook-service-cert
    status: {}
    ---
    apiVersion: admissionregistration.k8s.io/v1
    kind: MutatingWebhookConfiguration
    metadata:
      annotations:
        service.beta.openshift.io/inject-cabundle: "true"
      creationTimestamp: null
      labels:
        cluster.x-k8s.io/provider: infrastructure-azure
        clusterctl.cluster.x-k8s.io: ""
      name: capz-mutating-webhook-configuration
    webhooks:
    - admissionReviewVersions:
      - v1
      - v1beta1
      clientConfig:
        service:
          name: capz-webhook-service
          namespace: openshift-cluster-api
          path: /mutate-infrastructure-cluster-x-k8s-io-v1beta1-azuremachine
      failurePolicy: Fail
      matchPolicy: Equivalent
      name: default.azuremachine.infrastructure.cluster.x-k8s.io
      rules:
      - apiGroups:
        - infrastructure.cluster.x-k8s.io
        apiVersions:
        - v1beta1
        operations:
        - CREATE
        - UPDATE
        resources:
        - azuremachines
      sideEffects: None
    - admissionReviewVersions:
      - v1
      - v1beta1
      clientConfig:
        service:
          name: capz-webhook-service
          namespace: openshift-cluster-api
          path: /mutate-infrastructure-cluster-x-k8s-io-v1beta1-azuremachinetemplate
      failurePolicy: Fail
      matchPolicy: Equivalent
      name: default.azuremachinetemplate.infrastructure.cluster.x-k8s.io
      rules:
      - apiGroups:
        - infrastructure.cluster.x-k8s.io
        apiVersions:
        - v1beta1
        operations:
        - CREATE
        - UPDATE
        resources:
        - azuremachinetemplates
      sideEffects: None
    - admissionReviewVersions:
      - v1
      - v1beta1
      clientConfig:
        service:
          name: capz-webhook-service
          namespace: openshift-cluster-api
          path: /mutate-infrastructure-cluster-x-k8s-io-v1beta1-azuremachinepool
      failurePolicy: Fail
      name: default.azuremachinepool.infrastructure.cluster.x-k8s.io
      rules:
      - apiGroups:
        - infrastructure.cluster.x-k8s.io
        apiVersions:
        - v1beta1
        operations:
        - CREATE
        - UPDATE
        resources:
        - azuremachinepools
      sideEffects: None
    - admissionReviewVersions:
      - v1
      - v1beta1
      clientConfig:
        service:
          name: capz-webhook-service
          namespace: openshift-cluster-api
          path: /mutate-infrastructure-cluster-x-k8s-io-v1beta1-azuremanagedcontrolplane
      failurePolicy: Fail
      name: default.azuremanagedcontrolplanes.infrastructure.cluster.x-k8s.io
      rules:
      - apiGroups:
        - infrastructure.cluster.x-k8s.io
        apiVersions:
        - v1beta1
        operations:
        - CREATE
        - UPDATE
        resources:
        - azuremanagedcontrolplanes
      sideEffects: None
    - admissionReviewVersions:
      - v1
      - v1beta1
      clientConfig:
        service:
          name: capz-webhook-service
          namespace: openshift-cluster-api
          path: /mutate-infrastructure-cluster-x-k8s-io-v1beta1-azuremanagedmachinepool
      failurePolicy: Fail
      matchPolicy: Equivalent
      name: default.azuremanagedmachinepools.infrastructure.cluster.x-k8s.io
      rules:
      - apiGroups:
        - infrastructure.cluster.x-k8s.io
        apiVersions:
        - v1beta1
        operations:
        - CREATE
        - UPDATE
        resources:
        - azuremanagedmachinepools
      sideEffects: None
    ---
    apiVersion: admissionregistration.k8s.io/v1
    kind: ValidatingWebhookConfiguration
    metadata:
      annotations:
        service.beta.openshift.io/inject-cabundle: "true"
      creationTimestamp: null
      labels:
        cluster.x-k8s.io/provider: infrastructure-azure
        clusterctl.cluster.x-k8s.io: ""
      name: capz-validating-webhook-configuration
    webhooks:
    - admissionReviewVersions:
      - v1
      - v1beta1
      clientConfig:
        service:
          name: capz-webhook-service
          namespace: openshift-cluster-api
          path: /validate-infrastructure-cluster-x-k8s-io-v1beta1-azuremachine
      failurePolicy: Fail
      matchPolicy: Equivalent
      name: validation.azuremachine.infrastructure.cluster.x-k8s.io
      rules:
      - apiGroups:
        - infrastructure.cluster.x-k8s.io
        apiVersions:
        - v1beta1
        operations:
        - CREATE
        - UPDATE
        resources:
        - azuremachines
      sideEffects: None
    - admissionReviewVersions:
      - v1
      - v1beta1
      clientConfig:
        service:
          name: capz-webhook-service
          namespace: openshift-cluster-api
          path: /validate-infrastructure-cluster-x-k8s-io-v1beta1-azuremachinetemplate
      failurePolicy: Fail
      matchPolicy: Equivalent
      name: validation.azuremachinetemplate.infrastructure.cluster.x-k8s.io
      rules:
      - apiGroups:
        - infrastructure.cluster.x-k8s.io
        apiVersions:
        - v1beta1
        operations:
        - CREATE
        - UPDATE
        resources:
        - azuremachinetemplates
      sideEffects: None
    - admissionReviewVersions:
      - v1
      - v1beta1
      clientConfig:
        service:
          name: capz-webhook-service
          namespace: openshift-cluster-api
          path: /validate-infrastructure-cluster-x-k8s-io-v1beta1-azuremachinepool
      failurePolicy: Fail
      name: validation.azuremachinepool.infrastructure.cluster.x-k8s.io
      rules:
      - apiGroups:
        - infrastructure.cluster.x-k8s.io
        apiVersions:
        - v1beta1
        operations:
        - CREATE
        - UPDATE
        resources:
        - azuremachinepools
      sideEffects: None
    - admissionReviewVersions:
      - v1
      - v1beta1
      clientConfig:
        service:
          name: capz-webhook-service
          namespace: openshift-cluster-api
          path: /validate-infrastructure-cluster-x-k8s-io-v1beta1-azuremachinepoolmachine
      failurePolicy: Fail
      name: azuremachinepoolmachine.kb.io
      rules:
      - apiGroups:
        - infrastructure.cluster.x-k8s.io
        apiVersions:
        - v1beta1
        operations:
        - CREATE
        - UPDATE
        resources:
        - azuremachinepoolmachines
      sideEffects: None
    - admissionReviewVersions:
      - v1
      - v1beta1
      clientConfig:
        service:
          name: capz-webhook-service
          namespace: openshift-cluster-api
          path: /validate-infrastructure-cluster-x-k8s-io-v1beta1-azuremanagedcontrolplane
      failurePolicy: Fail
      name: validation.azuremanagedcontrolplanes.infrastructure.cluster.x-k8s.io
      rules:
      - apiGroups:
        - infrastructure.cluster.x-k8s.io
        apiVersions:
        - v1beta1
        operations:
        - CREATE
        - UPDATE
        resources:
        - azuremanagedcontrolplanes
      sideEffects: None
    - admissionReviewVersions:
      - v1
      - v1beta1
      clientConfig:
        service:
          name: capz-webhook-service
          namespace: openshift-cluster-api
          path: /validate-infrastructure-cluster-x-k8s-io-v1beta1-azuremanagedmachinepool
      failurePolicy: Fail
      matchPolicy: Equivalent
      name: validation.azuremanagedmachinepools.infrastructure.cluster.x-k8s.io
      rules:
      - apiGroups:
        - infrastructure.cluster.x-k8s.io
        apiVersions:
        - v1beta1
        operations:
        - UPDATE
        - DELETE
        resources:
        - azuremanagedmachinepools
      sideEffects: None
    ---
    apiVersion: v1
    kind: Service
    metadata:
      annotations:
        exclude.release.openshift.io/internal-openshift-hosted: "true"
        include.release.openshift.io/self-managed-high-availability: "true"
        include.release.openshift.io/single-node-developer: "true"
        release.openshift.io/feature-set: TechPreviewNoUpgrade
        service.beta.openshift.io/serving-cert-secret-name: capz-webhook-service-cert
      labels:
        cluster.x-k8s.io/provider: infrastructure-azure
        clusterctl.cluster.x-k8s.io: ""
      name: capz-webhook-service
      namespace: openshift-cluster-api
    spec:
      ports:
      - port: 443
        targetPort: webhook-server
      selector:
        cluster.x-k8s.io/provider: infrastructure-azure
  metadata: |
    # maps release series of major.minor to cluster-api contract version
    # the contract version may change between minor or major versions, but *not*
    # between patch versions.
    #
    # update this file only when a new major or minor version is released
    apiVersion: clusterctl.cluster.x-k8s.io/v1alpha3
    releaseSeries:
      - major: 0
        minor: 3
        contract: v1alpha2
      - major: 0
        minor: 4
        contract: v1alpha3
      - major: 0
        minor: 5
        contract: v1alpha4
      - major: 1
        minor: 0
        contract: v1beta1
      - major: 1
        minor: 1
        contract: v1beta1
      - major: 1
        minor: 2
        contract: v1beta1
      - major: 1
        minor: 3
        contract: v1beta1
      - major: 1
        minor: 4
        contract: v1beta1
      - major: 1
        minor: 5
        contract: v1beta1
      - major: 1
        minor: 6
        contract: v1beta1
      - major: 1
        minor: 7
        contract: v1beta1
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    provider.cluster.x-k8s.io/name: azure
    provider.cluster.x-k8s.io/type: infrastructure
    provider.cluster.x-k8s.io/version: v1.7.1
  name: azure
  namespace: openshift-cluster-api
