apiVersion: v1
data:
  components: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      creationTimestamp: null
      labels:
        cluster.x-k8s.io/provider: infrastructure-aws
        clusterctl.cluster.x-k8s.io: ""
        control-plane: capa-controller-manager
      name: capa-controller-manager
      namespace: openshift-cluster-api
    spec:
      replicas: 1
      selector:
        matchLabels:
          cluster.x-k8s.io/provider: infrastructure-aws
          control-plane: capa-controller-manager
      strategy: {}
      template:
        metadata:
          annotations:
            iam.amazonaws.com/role: ${AWS_CONTROLLER_IAM_ROLE:=""}
            target.workload.openshift.io/management: '{"effect": "PreferredDuringScheduling"}'
          creationTimestamp: null
          labels:
            cluster.x-k8s.io/provider: infrastructure-aws
            control-plane: capa-controller-manager
        spec:
          affinity:
            nodeAffinity:
              preferredDuringSchedulingIgnoredDuringExecution:
              - preference:
                  matchExpressions:
                  - key: ${K8S_CP_LABEL:=node-role.kubernetes.io/control-plane}
                    operator: Exists
                weight: 10
              - preference:
                  matchExpressions:
                  - key: node-role.kubernetes.io/master
                    operator: Exists
                weight: 10
          containers:
          - args:
            - --leader-elect
            - --v=${CAPA_LOGLEVEL:=0}
            - --metrics-bind-addr=127.0.0.1:8080
            env:
            - name: AWS_SHARED_CREDENTIALS_FILE
              value: /home/.aws/credentials
            image: to.be/replaced:v99
            imagePullPolicy: Always
            livenessProbe:
              failureThreshold: 3
              httpGet:
                path: /healthz
                port: healthz
              periodSeconds: 10
            name: manager
            ports:
            - containerPort: 9443
              name: webhook-server
              protocol: TCP
            - containerPort: 9440
              name: healthz
              protocol: TCP
            readinessProbe:
              httpGet:
                path: /readyz
                port: healthz
            resources:
              requests:
                cpu: 10m
                memory: 50Mi
            volumeMounts:
            - mountPath: /tmp/k8s-webhook-server/serving-certs
              name: cert
              readOnly: true
            - mountPath: /home/.aws
              name: credentials
          priorityClassName: system-cluster-critical
          securityContext:
            fsGroup: 1000
          serviceAccountName: capa-controller-manager
          terminationGracePeriodSeconds: 10
          tolerations:
          - effect: NoSchedule
            key: node-role.kubernetes.io/master
          - effect: NoSchedule
            key: node-role.kubernetes.io/control-plane
          volumes:
          - name: cert
            secret:
              defaultMode: 420
              secretName: capa-webhook-service-cert
          - name: credentials
            secret:
              secretName: capa-manager-bootstrap-credentials
    status: {}
    ---
    apiVersion: admissionregistration.k8s.io/v1
    kind: MutatingWebhookConfiguration
    metadata:
      annotations:
        service.beta.openshift.io/inject-cabundle: "true"
      creationTimestamp: null
      labels:
        cluster.x-k8s.io/provider: infrastructure-aws
        clusterctl.cluster.x-k8s.io: ""
      name: capa-mutating-webhook-configuration
    webhooks:
    - admissionReviewVersions:
      - v1
      - v1beta1
      clientConfig:
        service:
          name: capa-webhook-service
          namespace: openshift-cluster-api
          path: /mutate-infrastructure-cluster-x-k8s-io-v1beta2-awsmachine
      failurePolicy: Fail
      name: mutation.awsmachine.infrastructure.cluster.x-k8s.io
      rules:
      - apiGroups:
        - infrastructure.cluster.x-k8s.io
        apiVersions:
        - v1beta2
        operations:
        - CREATE
        - UPDATE
        resources:
        - awsmachines
      sideEffects: None
    - admissionReviewVersions:
      - v1
      - v1beta1
      clientConfig:
        service:
          name: capa-webhook-service
          namespace: openshift-cluster-api
          path: /mutate-infrastructure-cluster-x-k8s-io-v1beta2-awsfargateprofile
      failurePolicy: Fail
      matchPolicy: Equivalent
      name: default.awsfargateprofile.infrastructure.cluster.x-k8s.io
      rules:
      - apiGroups:
        - infrastructure.cluster.x-k8s.io
        apiVersions:
        - v1beta2
        operations:
        - CREATE
        - UPDATE
        resources:
        - awsfargateprofiles
      sideEffects: None
    - admissionReviewVersions:
      - v1
      - v1beta1
      clientConfig:
        service:
          name: capa-webhook-service
          namespace: openshift-cluster-api
          path: /mutate-infrastructure-cluster-x-k8s-io-v1beta2-awsmachinepool
      failurePolicy: Fail
      matchPolicy: Equivalent
      name: default.awsmachinepool.infrastructure.cluster.x-k8s.io
      rules:
      - apiGroups:
        - infrastructure.cluster.x-k8s.io
        apiVersions:
        - v1beta2
        operations:
        - CREATE
        - UPDATE
        resources:
        - awsmachinepools
      sideEffects: None
    - admissionReviewVersions:
      - v1
      - v1beta1
      clientConfig:
        service:
          name: capa-webhook-service
          namespace: openshift-cluster-api
          path: /mutate-infrastructure-cluster-x-k8s-io-v1beta2-awsmanagedmachinepool
      failurePolicy: Fail
      matchPolicy: Equivalent
      name: default.awsmanagedmachinepool.infrastructure.cluster.x-k8s.io
      rules:
      - apiGroups:
        - infrastructure.cluster.x-k8s.io
        apiVersions:
        - v1beta2
        operations:
        - CREATE
        - UPDATE
        resources:
        - awsmanagedmachinepools
      sideEffects: None
    - admissionReviewVersions:
      - v1
      - v1beta1
      clientConfig:
        service:
          name: capa-webhook-service
          namespace: openshift-cluster-api
          path: /mutate-bootstrap-cluster-x-k8s-io-v1beta2-eksconfig
      failurePolicy: Fail
      matchPolicy: Equivalent
      name: default.eksconfigs.bootstrap.cluster.x-k8s.io
      rules:
      - apiGroups:
        - bootstrap.cluster.x-k8s.io
        apiVersions:
        - v1beta2
        operations:
        - CREATE
        - UPDATE
        resources:
        - eksconfig
      sideEffects: None
    - admissionReviewVersions:
      - v1
      - v1beta1
      clientConfig:
        service:
          name: capa-webhook-service
          namespace: openshift-cluster-api
          path: /mutate-bootstrap-cluster-x-k8s-io-v1beta2-eksconfigtemplate
      failurePolicy: Fail
      matchPolicy: Equivalent
      name: default.eksconfigtemplates.bootstrap.cluster.x-k8s.io
      rules:
      - apiGroups:
        - bootstrap.cluster.x-k8s.io
        apiVersions:
        - v1beta2
        operations:
        - CREATE
        - UPDATE
        resources:
        - eksconfigtemplate
      sideEffects: None
    - admissionReviewVersions:
      - v1
      - v1beta1
      clientConfig:
        service:
          name: capa-webhook-service
          namespace: openshift-cluster-api
          path: /mutate-controlplane-cluster-x-k8s-io-v1beta2-awsmanagedcontrolplane
      failurePolicy: Fail
      matchPolicy: Equivalent
      name: default.awsmanagedcontrolplanes.controlplane.cluster.x-k8s.io
      rules:
      - apiGroups:
        - controlplane.cluster.x-k8s.io
        apiVersions:
        - v1beta2
        operations:
        - CREATE
        - UPDATE
        resources:
        - awsmanagedcontrolplanes
      sideEffects: None
    ---
    apiVersion: admissionregistration.k8s.io/v1
    kind: ValidatingWebhookConfiguration
    metadata:
      annotations:
        service.beta.openshift.io/inject-cabundle: "true"
      creationTimestamp: null
      labels:
        cluster.x-k8s.io/provider: infrastructure-aws
        clusterctl.cluster.x-k8s.io: ""
      name: capa-validating-webhook-configuration
    webhooks:
    - admissionReviewVersions:
      - v1
      - v1beta1
      clientConfig:
        service:
          name: capa-webhook-service
          namespace: openshift-cluster-api
          path: /validate-infrastructure-cluster-x-k8s-io-v1beta2-awsmachine
      failurePolicy: Fail
      matchPolicy: Equivalent
      name: validation.awsmachine.infrastructure.cluster.x-k8s.io
      rules:
      - apiGroups:
        - infrastructure.cluster.x-k8s.io
        apiVersions:
        - v1beta2
        operations:
        - CREATE
        - UPDATE
        resources:
        - awsmachines
      sideEffects: None
    - admissionReviewVersions:
      - v1
      - v1beta1
      clientConfig:
        service:
          name: capa-webhook-service
          namespace: openshift-cluster-api
          path: /validate-infrastructure-cluster-x-k8s-io-v1beta2-awsfargateprofile
      failurePolicy: Fail
      matchPolicy: Equivalent
      name: validation.awsfargateprofile.infrastructure.cluster.x-k8s.io
      rules:
      - apiGroups:
        - infrastructure.cluster.x-k8s.io
        apiVersions:
        - v1beta2
        operations:
        - CREATE
        - UPDATE
        resources:
        - awsfargateprofiles
      sideEffects: None
    - admissionReviewVersions:
      - v1
      - v1beta1
      clientConfig:
        service:
          name: capa-webhook-service
          namespace: openshift-cluster-api
          path: /validate-infrastructure-cluster-x-k8s-io-v1beta2-awsmachinepool
      failurePolicy: Fail
      matchPolicy: Equivalent
      name: validation.awsmachinepool.infrastructure.cluster.x-k8s.io
      rules:
      - apiGroups:
        - infrastructure.cluster.x-k8s.io
        apiVersions:
        - v1beta2
        operations:
        - CREATE
        - UPDATE
        resources:
        - awsmachinepools
      sideEffects: None
    - admissionReviewVersions:
      - v1
      - v1beta1
      clientConfig:
        service:
          name: capa-webhook-service
          namespace: openshift-cluster-api
          path: /validate-infrastructure-cluster-x-k8s-io-v1beta2-awsmanagedmachinepool
      failurePolicy: Fail
      matchPolicy: Equivalent
      name: validation.awsmanagedmachinepool.infrastructure.cluster.x-k8s.io
      rules:
      - apiGroups:
        - infrastructure.cluster.x-k8s.io
        apiVersions:
        - v1beta2
        operations:
        - CREATE
        - UPDATE
        resources:
        - awsmanagedmachinepools
      sideEffects: None
    - admissionReviewVersions:
      - v1
      - v1beta1
      clientConfig:
        service:
          name: capa-webhook-service
          namespace: openshift-cluster-api
          path: /validate-bootstrap-cluster-x-k8s-io-v1beta2-eksconfig
      failurePolicy: Fail
      matchPolicy: Equivalent
      name: validation.eksconfigs.bootstrap.cluster.x-k8s.io
      rules:
      - apiGroups:
        - bootstrap.cluster.x-k8s.io
        apiVersions:
        - v1beta2
        operations:
        - CREATE
        - UPDATE
        resources:
        - eksconfig
      sideEffects: None
    - admissionReviewVersions:
      - v1
      - v1beta1
      clientConfig:
        service:
          name: capa-webhook-service
          namespace: openshift-cluster-api
          path: /validate-bootstrap-cluster-x-k8s-io-v1beta2-eksconfigtemplate
      failurePolicy: Fail
      matchPolicy: Equivalent
      name: validation.eksconfigtemplates.bootstrap.cluster.x-k8s.io
      rules:
      - apiGroups:
        - bootstrap.cluster.x-k8s.io
        apiVersions:
        - v1beta2
        operations:
        - CREATE
        - UPDATE
        resources:
        - eksconfigtemplate
      sideEffects: None
    - admissionReviewVersions:
      - v1
      - v1beta1
      clientConfig:
        service:
          name: capa-webhook-service
          namespace: openshift-cluster-api
          path: /validate-controlplane-cluster-x-k8s-io-v1beta2-awsmanagedcontrolplane
      failurePolicy: Fail
      matchPolicy: Equivalent
      name: validation.awsmanagedcontrolplanes.controlplane.cluster.x-k8s.io
      rules:
      - apiGroups:
        - controlplane.cluster.x-k8s.io
        apiVersions:
        - v1beta2
        operations:
        - CREATE
        - UPDATE
        resources:
        - awsmanagedcontrolplanes
      sideEffects: None
    ---
    apiVersion: v1
    kind: Service
    metadata:
      annotations:
        exclude.release.openshift.io/internal-openshift-hosted: "true"
        include.release.openshift.io/self-managed-high-availability: "true"
        include.release.openshift.io/single-node-developer: "true"
        release.openshift.io/feature-set: TechPreviewNoUpgrade
        service.beta.openshift.io/serving-cert-secret-name: capa-webhook-service-cert
      labels:
        cluster.x-k8s.io/provider: infrastructure-aws
        clusterctl.cluster.x-k8s.io: ""
      name: capa-webhook-service
      namespace: openshift-cluster-api
    spec:
      ports:
      - port: 443
        targetPort: webhook-server
      selector:
        cluster.x-k8s.io/provider: infrastructure-aws
  metadata: |
    # maps release series of major.minor to cluster-api contract version
    # the contract version may change between minor or major versions, but *not*
    # between patch versions.
    #
    # update this file only when a new major or minor version is released
    apiVersion: clusterctl.cluster.x-k8s.io/v1alpha3
    releaseSeries:
      - major: 0
        minor: 4
        contract: v1alpha2
      - major: 0
        minor: 5
        contract: v1alpha3
      - major: 0
        minor: 6
        contract: v1alpha3
      - major: 0
        minor: 7
        contract: v1alpha4
      - major: 1
        minor: 0
        contract: v1beta1
      - major: 1
        minor: 1
        contract: v1beta1
      - major: 1
        minor: 2
        contract: v1beta1
      - major: 1
        minor: 3
        contract: v1beta1
      - major: 1
        minor: 4
        contract: v1beta1
      - major: 1
        minor: 5
        contract: v1beta1
      - major: 2
        minor: 0
        contract: v1beta1
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    provider.cluster.x-k8s.io/name: aws
    provider.cluster.x-k8s.io/type: infrastructure
    provider.cluster.x-k8s.io/version: v2.0.2
  name: aws
  namespace: openshift-cluster-api
