apiVersion: v1
data:
  components: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      creationTimestamp: null
      labels:
        cluster.x-k8s.io/provider: cluster-api
        clusterctl.cluster.x-k8s.io: ""
        control-plane: controller-manager
      name: capi-controller-manager
      namespace: openshift-cluster-api
    spec:
      replicas: 1
      selector:
        matchLabels:
          cluster.x-k8s.io/provider: cluster-api
          control-plane: controller-manager
      strategy: {}
      template:
        metadata:
          annotations:
            target.workload.openshift.io/management: '{"effect": "PreferredDuringScheduling"}'
          creationTimestamp: null
          labels:
            cluster.x-k8s.io/provider: cluster-api
            control-plane: controller-manager
        spec:
          containers:
          - args:
            - --leader-elect
            - --metrics-bind-addr=localhost:8080
            command:
            - /manager
            env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_UID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.uid
            image: to.be/replaced:v99
            imagePullPolicy: Always
            livenessProbe:
              httpGet:
                path: /healthz
                port: healthz
            name: manager
            ports:
            - containerPort: 9443
              name: webhook-server
              protocol: TCP
            - containerPort: 9440
              name: healthz
              protocol: TCP
            readinessProbe:
              httpGet:
                path: /readyz
                port: healthz
            resources:
              requests:
                cpu: 10m
                memory: 50Mi
            volumeMounts:
            - mountPath: /tmp/k8s-webhook-server/serving-certs
              name: cert
              readOnly: true
          priorityClassName: system-cluster-critical
          serviceAccountName: capi-manager
          terminationGracePeriodSeconds: 10
          tolerations:
          - effect: NoSchedule
            key: node-role.kubernetes.io/master
          - effect: NoSchedule
            key: node-role.kubernetes.io/control-plane
          volumes:
          - name: cert
            secret:
              secretName: capi-webhook-service-cert
    status: {}
    ---
    apiVersion: admissionregistration.k8s.io/v1
    kind: MutatingWebhookConfiguration
    metadata:
      annotations:
        service.beta.openshift.io/inject-cabundle: "true"
      creationTimestamp: null
      labels:
        cluster.x-k8s.io/provider: cluster-api
        clusterctl.cluster.x-k8s.io: ""
      name: capi-mutating-webhook-configuration
    webhooks:
    - admissionReviewVersions:
      - v1
      - v1beta1
      clientConfig:
        service:
          name: capi-webhook-service
          namespace: openshift-cluster-api
          path: /mutate-cluster-x-k8s-io-v1beta1-machine
      failurePolicy: Fail
      matchPolicy: Equivalent
      name: default.machine.cluster.x-k8s.io
      rules:
      - apiGroups:
        - cluster.x-k8s.io
        apiVersions:
        - v1beta1
        operations:
        - CREATE
        - UPDATE
        resources:
        - machines
      sideEffects: None
    - admissionReviewVersions:
      - v1
      - v1beta1
      clientConfig:
        service:
          name: capi-webhook-service
          namespace: openshift-cluster-api
          path: /mutate-cluster-x-k8s-io-v1beta1-machinedeployment
      failurePolicy: Fail
      matchPolicy: Equivalent
      name: default.machinedeployment.cluster.x-k8s.io
      rules:
      - apiGroups:
        - cluster.x-k8s.io
        apiVersions:
        - v1beta1
        operations:
        - CREATE
        - UPDATE
        resources:
        - machinedeployments
      sideEffects: None
    - admissionReviewVersions:
      - v1
      - v1beta1
      clientConfig:
        service:
          name: capi-webhook-service
          namespace: openshift-cluster-api
          path: /mutate-cluster-x-k8s-io-v1beta1-machinehealthcheck
      failurePolicy: Fail
      matchPolicy: Equivalent
      name: default.machinehealthcheck.cluster.x-k8s.io
      rules:
      - apiGroups:
        - cluster.x-k8s.io
        apiVersions:
        - v1beta1
        operations:
        - CREATE
        - UPDATE
        resources:
        - machinehealthchecks
      sideEffects: None
    - admissionReviewVersions:
      - v1
      - v1beta1
      clientConfig:
        service:
          name: capi-webhook-service
          namespace: openshift-cluster-api
          path: /mutate-cluster-x-k8s-io-v1beta1-machineset
      failurePolicy: Fail
      matchPolicy: Equivalent
      name: default.machineset.cluster.x-k8s.io
      rules:
      - apiGroups:
        - cluster.x-k8s.io
        apiVersions:
        - v1beta1
        operations:
        - CREATE
        - UPDATE
        resources:
        - machinesets
      sideEffects: None
    - admissionReviewVersions:
      - v1
      - v1beta1
      clientConfig:
        service:
          name: capi-webhook-service
          namespace: openshift-cluster-api
          path: /mutate-runtime-cluster-x-k8s-io-v1alpha1-extensionconfig
      failurePolicy: Fail
      matchPolicy: Equivalent
      name: default.extensionconfig.runtime.addons.cluster.x-k8s.io
      rules:
      - apiGroups:
        - runtime.cluster.x-k8s.io
        apiVersions:
        - v1alpha1
        operations:
        - CREATE
        - UPDATE
        resources:
        - extensionconfigs
      sideEffects: None
    - admissionReviewVersions:
      - v1
      - v1beta1
      clientConfig:
        service:
          name: capi-webhook-service
          namespace: openshift-cluster-api
          path: /mutate-cluster-x-k8s-io-v1beta1-machinepool
      failurePolicy: Fail
      matchPolicy: Equivalent
      name: default.machinepool.cluster.x-k8s.io
      rules:
      - apiGroups:
        - cluster.x-k8s.io
        apiVersions:
        - v1beta1
        operations:
        - CREATE
        - UPDATE
        resources:
        - machinepools
      sideEffects: None
    ---
    apiVersion: admissionregistration.k8s.io/v1
    kind: ValidatingWebhookConfiguration
    metadata:
      annotations:
        service.beta.openshift.io/inject-cabundle: "true"
      creationTimestamp: null
      labels:
        cluster.x-k8s.io/provider: cluster-api
        clusterctl.cluster.x-k8s.io: ""
      name: capi-validating-webhook-configuration
    webhooks:
    - admissionReviewVersions:
      - v1
      - v1beta1
      clientConfig:
        service:
          name: capi-webhook-service
          namespace: openshift-cluster-api
          path: /validate-cluster-x-k8s-io-v1beta1-machine
      failurePolicy: Fail
      matchPolicy: Equivalent
      name: validation.machine.cluster.x-k8s.io
      rules:
      - apiGroups:
        - cluster.x-k8s.io
        apiVersions:
        - v1beta1
        operations:
        - CREATE
        - UPDATE
        resources:
        - machines
      sideEffects: None
    - admissionReviewVersions:
      - v1
      - v1beta1
      clientConfig:
        service:
          name: capi-webhook-service
          namespace: openshift-cluster-api
          path: /validate-cluster-x-k8s-io-v1beta1-machinedeployment
      failurePolicy: Fail
      matchPolicy: Equivalent
      name: validation.machinedeployment.cluster.x-k8s.io
      rules:
      - apiGroups:
        - cluster.x-k8s.io
        apiVersions:
        - v1beta1
        operations:
        - CREATE
        - UPDATE
        resources:
        - machinedeployments
      sideEffects: None
    - admissionReviewVersions:
      - v1
      - v1beta1
      clientConfig:
        service:
          name: capi-webhook-service
          namespace: openshift-cluster-api
          path: /validate-cluster-x-k8s-io-v1beta1-machinehealthcheck
      failurePolicy: Fail
      matchPolicy: Equivalent
      name: validation.machinehealthcheck.cluster.x-k8s.io
      rules:
      - apiGroups:
        - cluster.x-k8s.io
        apiVersions:
        - v1beta1
        operations:
        - CREATE
        - UPDATE
        resources:
        - machinehealthchecks
      sideEffects: None
    - admissionReviewVersions:
      - v1
      - v1beta1
      clientConfig:
        service:
          name: capi-webhook-service
          namespace: openshift-cluster-api
          path: /validate-cluster-x-k8s-io-v1beta1-machineset
      failurePolicy: Fail
      matchPolicy: Equivalent
      name: validation.machineset.cluster.x-k8s.io
      rules:
      - apiGroups:
        - cluster.x-k8s.io
        apiVersions:
        - v1beta1
        operations:
        - CREATE
        - UPDATE
        resources:
        - machinesets
      sideEffects: None
    - admissionReviewVersions:
      - v1
      - v1beta1
      clientConfig:
        service:
          name: capi-webhook-service
          namespace: openshift-cluster-api
          path: /validate-runtime-cluster-x-k8s-io-v1alpha1-extensionconfig
      failurePolicy: Fail
      matchPolicy: Equivalent
      name: validation.extensionconfig.runtime.cluster.x-k8s.io
      rules:
      - apiGroups:
        - runtime.cluster.x-k8s.io
        apiVersions:
        - v1alpha1
        operations:
        - CREATE
        - UPDATE
        resources:
        - extensionconfigs
      sideEffects: None
    - admissionReviewVersions:
      - v1
      - v1beta1
      clientConfig:
        service:
          name: capi-webhook-service
          namespace: openshift-cluster-api
          path: /validate-cluster-x-k8s-io-v1beta1-machinepool
      failurePolicy: Fail
      matchPolicy: Equivalent
      name: validation.machinepool.cluster.x-k8s.io
      rules:
      - apiGroups:
        - cluster.x-k8s.io
        apiVersions:
        - v1beta1
        operations:
        - CREATE
        - UPDATE
        resources:
        - machinepools
      sideEffects: None
    - admissionReviewVersions:
      - v1
      - v1beta1
      clientConfig:
        service:
          name: capi-webhook-service
          namespace: openshift-cluster-api
          path: /validate-addons-cluster-x-k8s-io-v1beta1-clusterresourceset
      failurePolicy: Fail
      matchPolicy: Equivalent
      name: validation.clusterresourceset.addons.cluster.x-k8s.io
      rules:
      - apiGroups:
        - addons.cluster.x-k8s.io
        apiVersions:
        - v1beta1
        operations:
        - CREATE
        - UPDATE
        resources:
        - clusterresourcesets
      sideEffects: None
    - admissionReviewVersions:
      - v1
      - v1beta1
      clientConfig:
        service:
          name: capi-webhook-service
          namespace: openshift-cluster-api
          path: /validate-ipam-cluster-x-k8s-io-v1alpha1-ipaddress
      failurePolicy: Fail
      matchPolicy: Equivalent
      name: validation.ipaddress.ipam.cluster.x-k8s.io
      rules:
      - apiGroups:
        - ipam.cluster.x-k8s.io
        apiVersions:
        - v1alpha1
        operations:
        - CREATE
        - UPDATE
        - DELETE
        resources:
        - ipaddresses
      sideEffects: None
    - admissionReviewVersions:
      - v1
      - v1beta1
      clientConfig:
        service:
          name: capi-webhook-service
          namespace: openshift-cluster-api
          path: /validate-ipam-cluster-x-k8s-io-v1alpha1-ipaddressclaim
      failurePolicy: Fail
      matchPolicy: Equivalent
      name: validation.ipaddressclaim.ipam.cluster.x-k8s.io
      rules:
      - apiGroups:
        - ipam.cluster.x-k8s.io
        apiVersions:
        - v1alpha1
        operations:
        - CREATE
        - UPDATE
        - DELETE
        resources:
        - ipaddressclaims
      sideEffects: None
    ---
    apiVersion: v1
    kind: Service
    metadata:
      annotations:
        exclude.release.openshift.io/internal-openshift-hosted: "true"
        include.release.openshift.io/self-managed-high-availability: "true"
        include.release.openshift.io/single-node-developer: "true"
        release.openshift.io/feature-set: TechPreviewNoUpgrade
        service.beta.openshift.io/serving-cert-secret-name: capi-webhook-service-cert
      labels:
        cluster.x-k8s.io/provider: cluster-api
        clusterctl.cluster.x-k8s.io: ""
      name: capi-webhook-service
      namespace: openshift-cluster-api
    spec:
      ports:
      - port: 443
        targetPort: webhook-server
      selector:
        cluster.x-k8s.io/provider: cluster-api
  metadata: |
    # maps release series of major.minor to cluster-api contract version
    # the contract version may change between minor or major versions, but *not*
    # between patch versions.
    #
    # update this file only when a new major or minor version is released
    apiVersion: clusterctl.cluster.x-k8s.io/v1alpha3
    kind: Metadata
    releaseSeries:
      - major: 1
        minor: 3
        contract: v1beta1
      - major: 1
        minor: 2
        contract: v1beta1
      - major: 1
        minor: 1
        contract: v1beta1
      - major: 1
        minor: 0
        contract: v1beta1
      - major: 0
        minor: 4
        contract: v1alpha4
      - major: 0
        minor: 3
        contract: v1alpha3
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    provider.cluster.x-k8s.io/name: cluster-api
    provider.cluster.x-k8s.io/type: core
    provider.cluster.x-k8s.io/version: v1.3.3
  name: cluster-api
  namespace: openshift-cluster-api
